apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-test
  labels:
    app: nodeapp
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: 9967550479/nodeapp:v6
        ports:
                - containerPort: 3000
